### ISSUE TITLE
ImportError: cannot import name 'Api' from 'pyfacebook'

### ISSUE THREAD

**Issue by dyna92** [sns-sdks/python-facebook#100]
i tried to run the get_publics_post.py example on jetbrains and i got this error

ImportError: cannot import name 'Api' from 'pyfacebook'
![test](https://user-images.githubusercontent.com/58147942/111707593-a0b06300-8844-11eb-8cf2-a89cfdf80c6c.png)

**Comment by MerleLiuKun** [comment]
What your command for pip?  Is `pip install python-facebook-api` ?

**Comment by dyna92** [comment]
i run the command, but then i got this . ask me to upgrade pip version 
![pip](https://user-images.githubusercontent.com/58147942/111747224-5b655300-888f-11eb-8c90-6e9642ea818b.png)

but still i got all this erros !!!!

**Comment by dyna92** [comment]
i succeded to install the last version of pip,but still the same problem 
i am running the code into pycharm 
![pip2](https://user-images.githubusercontent.com/58147942/111749016-82248900-8891-11eb-9c44-975afc70f033.png)

**Comment by dyna92** [comment]
i finally update the pip, it didnt work before because i didnt trun the cmd as administrator !!! thanks
