### ISSUE TITLE
Cant acces public page content with  Api.get_pages_post()

### ISSUE THREAD

**Issue by dyna92** [sns-sdks/python-facebook#102]
i m trying to run the example provided , 
i got this error 
pyfacebook.error.PyFacebookException: FacebookException(code=10,type=OAuthException,message=(#10) This endpoint requires the 'pages_read_engagement' permission or the 'Page Public Content Access' feature. Refer to https://developers.facebook.com/docs/apps/review/login-permissions#manage-pages and https://developers.facebook.com/
docs/apps/review/feature#reference-PAGES_ACCESS for details.)

**Comment by MerleLiuKun** [comment]
Do you have an app and have been got `Page Public Content Access` permission  by facebook?
