### ISSUE TITLE
ImportError: cannot import name 'GraphAPI' from 'pyfacebook'

### ISSUE THREAD

**Issue by achampagne1** [sns-sdks/python-facebook#183]
I tried running this small snippet of code:
`from pyfacebook import GraphAPI`
`api = GraphAPI(access_token="token")`
but I got the error:
`ImportError: cannot import name 'GraphAPI' from 'pyfacebook' (/home/ec2-user/.local/lib/python3.7/site-packages/pyfacebook/__init__.py)`
I am using amazon web services EC2. What is the solution to this?

**Comment by achampagne1** [comment]
I deleted the package and redownloaded, and it worked

**Comment by tauseedzaman** [comment]
i got the same issue. is there any other solution to this
