### ISSUE TITLE
groups?

### ISSUE THREAD

**Issue by Ketsby69** [sns-sdks/python-facebook#190]
How can I bring all the posts of a group, do you have any code example?

**Comment by MerleLiuKun** [comment]
If you want to get the posts for a group, just like get page's posts.

If you are using the `GraphAPI`, The code may

```
from pyfacebook import GraphAPI
api = GraphAPI(access_token="xxx")

posts = api.get_connection(object_id="group_id", connection="posts")
```

If you are using the `FacebookApi`.

```
from pyfacebook import FacebookApi
api = FacebookApi(access_token="xxxx")

api.group.get_feed(object_id="group id")
```
