### ISSUE TITLE
LiveVideo comment

### ISSUE THREAD

**Issue by ObedH26** [sns-sdks/python-facebook#193]
Hi there,
Do this API support looking for live video's comment (I'm wondering for facebook but also ig), like checking if the userid has some live working out and picking its comment in real time ? I mean it would be neat if the live dont have to be launched from the developers app, anyway what's about it guys ?

**Comment by MerleLiuKun** [comment]
This library only support send requests by the `Graph API` provided by the facebook.  So I don't konw your mean?

**Comment by gitagogaming** [comment]
I am also looking to get live video comments from a Facebook live feed.. 

Ive figured out how to get a video post and any polls for that video but cannot seem to find comments/messages associated with it just yet. 

was wondering if you have learned anymore about this since last?

**Comment by MerleLiuKun** [comment]
> https://developers.facebook.com/docs/graph-api/server-sent-events/endpoints/live-comments/

This may a stream request, Maybe you can try it. Just set the request mode to `stream`.

And another way, I think you can use the webhook provided by facebook. You can see the docs at https://developers.facebook.com/docs/graph-api/webhooks.

**Comment by MerleLiuKun** [comment]
This #211  cover the Server-Sent-Events API. :)
