### ISSUE TITLE
Examples - How to post an image to Instagram Business?

### ISSUE THREAD

**Issue by r3dh0t** [sns-sdks/python-facebook#194]
I'm trying to understand how to use this libary to create a post for Instagram Business. Is there some documentation with this already, or if not, can you point me in the right direction please?

**Comment by MerleLiuKun** [comment]
As for current version.

First you need know the api docs for publish a media.  

Available docs: 
- https://developers.facebook.com/docs/instagram-api/reference/ig-user/media
- https://developers.facebook.com/docs/instagram-api/reference/ig-user/media_publish

Then I think you can use the `GraphAPI` class to post a media.  just a demo for publish a image media:

Initial class 

``` python
from pyfacebook import GraphAPI

api = GraphAPI(access_token="access token")  # notice the access token need have publish permissions.
object_id = "business ID"   # target business account id
```

Then create a container to publish.
```python
resp = api.post_object(
    object_id=object_id,
    connection="media",
    params={
        "image_url": "public url for image",
        "caption": "Image published by api",
    }
)
print(resp)
# {'id': '17952987976782688'}
```

Then publish the container.

```python
publish_resp = api.post_object(
    object_id=object_id,
    connection="media_publish",
    params={
        "creation_id": "17952987976782688",
    }
)
print(publish_resp)
# {'id': '17899702154554435'}
```
Now you can see the media has published success.
