### ISSUE TITLE
Sample code not working

### ISSUE THREAD

**Issue by Gautamshahi** [sns-sdks/python-facebook#195]
I am not able to execute the sample code

![image](https://user-images.githubusercontent.com/3966230/162625438-fa4f978c-8cc0-4113-ad17-6b519615fd9e.png)

What is the reason for it?

**Comment by MerleLiuKun** [comment]
Hey,  

first, Your secret have show in the picture.  You need regenerate it to protect your app.

Then, I think you make some wrong for the Api class provided by the library.

If you want to use `api.user.get_info()`, You need initial the `api` with `FacebookAPI` class. Not the `GraphAPI` class.
