### ISSUE TITLE
Setting app level state

### ISSUE THREAD

**Issue by ArnoldGihozo** [sns-sdks/python-facebook#200]
Hello! Currently making my way through the source code on here! I noticed that within the oauth flow, the state is set-automatically at the class level as seen [here](https://github.com/sns-sdks/python-facebook/blob/8c6ab5aed5859ea2133d1868ef0fd768040bbffb/pyfacebook/api/graph.py#L22-L38). With that then, whenever the oauth session is requested, only that state is grabbed instead of the one that I can pass through the` **kwargs`. Is there a way for me to set my own state?

Thankyou!

**Comment by MerleLiuKun** [comment]
Good idea!  May we need to support set this state in initial variables.  

I will change this in next release!

Thanks!
