### ISSUE TITLE
Post Class repr throws error with image-only posts

### ISSUE THREAD

**Issue by jsradford** [sns-sdks/python-facebook#205]
This took a while to debug, but when you try to get a post from a user without any text (i.e. someone just posts an image without any text) line 131 in models/post.py: message = f"{self.message[:30]}..." throws an error.

You can fix it by having it just print out the ids or checking to see if message is empty before trying to slice it

**Comment by MerleLiuKun** [comment]
oh, this is bug.

Thanks for you, I will fix it quickly,:)
