### ISSUE TITLE
Creating an auth flow to retrieve a token for new users of application

### ISSUE THREAD

**Issue by gitagogaming** [sns-sdks/python-facebook#208]
I have created an app which I intend on releasing  for public use, it will not use any sort of webservers and will only run on their local computer allowing them to see their live videos/comments/reactions etc..

I would prefer not to have them go thru any sort of developer console and just be able to authenticate the app to access their data and then it would be hands free for them at that point

I've been looking around a bit for examples and just can not seem to find one

i also thought I recalled seeing an issue somewhere that mentions a google group for support/questions in regards to.  If there is such a thing please feel free to link it here again I'd appreciate it.

**Comment by MerleLiuKun** [comment]
Maybe  you can get some information from [webhooks docs](https://developers.facebook.com/docs/graph-api/webhooks) .

**Comment by BOVAGE** [comment]
I think what @gitagogaming needed was OAuth 2.0 Device Authorization Grant flow. I wrote about doing something similar ( Facebook login for a Discord bot - without creating a web server to handle redirection). You can read about it [here](https://earthly.dev/blog/oauth-2-in-non-web-clients/).
