### ISSUE TITLE
Add API to enable instagram business account to publish content

### ISSUE THREAD

**Issue by BOVAGE** [sns-sdks/python-facebook#215]
Hello!
Thanks for developing and maintaining this project.

I checked and searched through the codebase. It seems content publishing for Instagram business accounts has not been implemented.

I will like to add this functionality to the package.

I will appreciate it if you could assign this to me and inform me of any information I need to know as regards contributing.
Regards.

**Comment by MerleLiuKun** [comment]
wow! welcome :)  I will have some time at weekend,  Then  i will reply to you!

**Comment by MerleLiuKun** [comment]
Sorry for late reply.

Now, this library support to use the `GraphAPI` class to send the `post_object` method to publish the media.

So  I think you want to add some functions to the `IGBusinessApi` class and with the `dataclass` mode.

If I understand well, give me reply. :)

**Comment by BOVAGE** [comment]
Hello. I forgot to update you. The `post_object` method from `GraphAPI` class works for content publishing.

I have a question though.
Don't you think the `post_object` method is doing too much? I think it's more intuitive to look for publish media, publish carousel post ... under the `IGBusinessAPI` class

Sorry for late reply.

**Comment by MerleLiuKun** [comment]
Yes, you are right.

`post_object` is a common method for the requests to send `POST` request,  

And the `IGBusinessAPI` is the extend for the `GraphAPI` to make people use instagram api more easily. 

And very welcome to pr for this shorts.
