### ISSUE TITLE
exchange_long_lived_page_access_token wrong connection

### ISSUE THREAD

**Issue by lluc2397** [sns-sdks/python-facebook#219]
When calling the method exchange_long_lived_page_access_token of the API class y get the following exception

pyfacebook.exceptions.FacebookError: FacebookError(code=100,message=(#100) Tried accessing nonexisting field (accounts) on node type (Page),type=OAuthException,fbtrace_id=AblWlhmwS_6ebMzoggXzdRs)

**Comment by MerleLiuKun** [comment]
This method need `ID for user`. Not `ID for page`.

And this method to get all pages basic fields(with access token) for a facebook user.
