### ISSUE TITLE
Unable to access public page content

### ISSUE THREAD

**Issue by darkhash** [sns-sdks/python-facebook#22]
page_info = self.api.get_page_info(page_id='20531316728')

On trying to access the page info like above I am getting error as below,

pyfacebook.error.PyFacebookError: {'message': '(#100) Pages Public Content Access requires either app secret proof or an app token', 'type': 'OAuthException', 'code': 100, 'fbtrace_id': 'ACYiJkevpIouKlDsqNtSq-9'}

**Comment by MerleLiuKun** [comment]
Hi, as the response says, this need `Pages Public Content Access ` permission. You can do app permission's apply follow this content: [App Review](https://developers.facebook.com/docs/apps/review). Before your review approved, you can only get your self page's data or app's tester's page data.

**Comment by MerleLiuKun** [comment]
Oops.  I also get this error.  Since facebook graph api `v5.0`, some changed.

> Requests made to endpoints that require the Page Public Content Access feature must be made with either an App Access Token or include the app's App Secret. If the calling app has been granted the manage_pages permission however, an app access token or app secret is not required.

And new created app, has a default version is `v5.0`。 This is a big change. I will fix it soon.
