### ISSUE TITLE
Update version on Pypi

### ISSUE THREAD

**Issue by astagi** [sns-sdks/python-facebook#231]
Hello! Thanks for this library, please update the current version on Pypi, at the moment I'm forced to use this in my requirements

```txt
-e git+https://github.com/sns-sdks/python-facebook.git@34460731b314a577c559e1764e575d82d94b64d4#egg=python-facebook-api
```

**Comment by MerleLiuKun** [comment]
I will make a release this week! :)

**Comment by astagi** [comment]
Thank you so much!
