### ISSUE TITLE
Typo in `GraphAPI.debug_token`'s docstring

### ISSUE THREAD

**Issue by nbro10** [sns-sdks/python-facebook#237]
```
"""
Get input token info by issued app administrator's access token
:param input_token: Access token to debug.
:param access_token:
:return: Issued app administrator's access token
"""
```

Maybe you meant 

```
Get the input token info issued by the app administrator's access token
```

?

But then what's the difference between the "input token" and the "app administrator's access token"

It might be a good idea to base the description of this method on what is written here: https://developers.facebook.com/docs/facebook-login/guides/%20access-tokens/debugging.

**Comment by MerleLiuKun** [comment]
hi,

You can use the [app's token](https://developers.facebook.com/docs/facebook-login/guides/access-tokens/#apptokens).

example：

If you have an access token `ac=xxxxx`

And you must have the app which the access token belonged to,  then you must have the app's token,

So then you can do this.

```
api.debug_token(input_token="token which you want to debug,  just `ac`", access_token="your facebook app's token")
```
:)

**Comment by MerleLiuKun** [comment]
Yes we can generate the app token just with the `app_id` and `app_secret`. 

Now if you initial app instance as follows:

```
api = GraphAPI(
    app_id="xxx",
    app_secret="xxx",
    application_only_auth=True
)
```
Now this method will automatically to use `app token`
