### ISSUE TITLE
IgProApi cannot be imported?

### ISSUE THREAD

**Issue by diavy** [sns-sdks/python-facebook#32]
I tried to use:
from pyfacebook.api.instagram import IgProApi
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from pyfacebook.api.instagram import IgProApi
ImportError: cannot import name 'IgProApi' from 'pyfacebook.api.instagram' (/usr/local/lib/python3.7/site-packages/pyfacebook/api/instagram.py)

In addition, hope you can add more instagraph API functionalities soon! like insights, mentions, tag search, etc..

**Comment by MerleLiuKun** [comment]
I have not found the error when call 

 ``` python 
from pyfacebook.api.instagram import IgProApi
from pyfacebook import IgProApi
```
I prefer to the second way.  Can you show more code for your env?

And thanks for your advice.  Those follows functions I am doing now. Give me sometime. :)

**Comment by diavy** [comment]
> I have not found the error when call
> 
> ```python
> from pyfacebook.api.instagram import IgProApi
> from pyfacebook import IgProApi
> ```
> 
> I prefer to the second way. Can you show more code for your env?
> 

I tried both **from pyfacebook.api.instagram import IgProApi** and 
**from pyfacebook import IgProApi** but neither works for me. 


> from pyfacebook import IgProApi
> Traceback (most recent call last):
>   File "/Users/U6026806/Desktop/ig_api_test.py", line 1, in <module>
>     from pyfacebook import IgProApi
> ImportError: cannot import name 'IgProApi'

The only way I can use your library is to download it to my local machine and import module from the source code package. I cannot use it through "pip install ***"

However, **from pyfacebook import Api works** for me. but not IgProApi. Could you please check the configuration of IgProApi?

> And thanks for your advice. Those follows functions I am doing now. Give me sometime. :)
Looking forward to it very much!!

**Comment by diavy** [comment]
HI, Another question I want to confirm with you:
For the function like 

> api.get_media_info(media_id=****)

It works if I want to get the info of a picture posted from my own account, but I cannot call it from other's account. Otherwise, there'r permission error. Is it true?

**Comment by MerleLiuKun** [comment]
> The only way I can use your library is to download it to my local machine and import module from the source code package. I cannot use it through "pip install ***"

Oh, what your command for pip, there already have a package named `pyfacebook` but not this.  
For this package, need run command `pip install python-facebook-api` 。  
So can you check this?


> It works if I want to get the info of a picture posted from my own account, but I cannot call it from other's account. Otherwise, there'r permission error. Is it true?

Yes,  your have not permission to get another account's media by this method.   If you want to get other's account. need use the method `discovery-xxx`.  And the discovery maybe only get [business account](https://www.facebook.com/help/instagram/502981923235522)  data by his username.

**Comment by diavy** [comment]
Thanks for you replies and those are very helpful.
With regards to the problem of get the media metadata from other's account, yes I used 
`discovery_user_medias` and get a list of medias returned. Then I want to check the metadata of each media in the list, I found the some fileds, like timestamp, likes_count, etc; However, other fields are 'None', like comments. I'm wondering **is it possible for me to get those comments/reply content**? I tried to use `get_medias_info`, but having permission error again.

**Comment by MerleLiuKun** [comment]
Sorry for the late reply.

> **is it possible for me to get those comments/reply content**?

Now we can not get other account's comments if we not have their permission. 

You can only use methods for `get_xxx` for yourself or the account which you have enough permissions.

**Comment by diavy** [comment]
> Now we can not get other account's comments if we not have their permission.
> 
> You can only use methods for `get_xxx` for yourself or the account which you have enough permissions.

Thanks for the confirmation. Again,  looking forward to other cool functionalities from instagram graph API to be added! Especially, the **Tag Search** which seems to be another powerful tool to explore others accounts, in addition to **discover_XX_XX**.

**Comment by MerleLiuKun** [comment]
😄 Yes, You are right, I am too busy recently, and I will add remain method quickly.  Thanks for you again.:)

**Comment by MerleLiuKun** [comment]
#39  Has provided those methods.
