### ISSUE TITLE
get post mentioning @username? get content of comments?

### ISSUE THREAD

**Issue by diavy** [sns-sdks/python-facebook#43]
HI, Thanks for your updating. Your API helps me a lot! 
I have two more questions to confirm:
(1) Is it possible for me to get all medias mentioning an IG account @username?
(2) through business discovery, I can get the metadata of all of a posted user's media. For each media, can I get the textual content of each comment?

My gut feeling is that I cannot get the above two, due to the access token authorization. But I want to confirm with you, because you're very familiar with it. thanks:)

**Comment by MerleLiuKun** [comment]
Well, as for medias and comments, you need to get the user access token for the target account. 
You can see it at [Permissions](https://developers.facebook.com/docs/instagram-api/reference/user/mentioned_media#Permissions), [comments](https://developers.facebook.com/docs/instagram-api/reference/media/comments#Permissions)。

If you have the access token for the @username, you can get the data.

And, discovery method only return the public data. :)
