### ISSUE TITLE
No data in insights

### ISSUE THREAD

**Issue by Krishnacore** [sns-sdks/python-facebook#55]
**Request:** 
api.get_user_insights(user_id=api.instagram_business_id, period="day", metrics=["impressions", "reach"])

**Expected Result:**
[IgProInsight(name='impressions', period='day', values=[IgProInsightValue(value=1038, end_time='2020-01-08T08:00:00+0000'), IgProInsightValue(value=136, end_time='2020-01-09T08:00:00+0000')]),
 IgProInsight(name='reach', period='day', values=[IgProInsightValue(value=751, end_time='2020-01-08T08:00:00+0000'), IgProInsightValue(value=54, end_time='2020-01-09T08:00:00+0000')])]

**Real result:**
[IgProInsight(name='impressions', period='day'), IgProInsight(name='reach', period='day')] without any value

**Comment by MerleLiuKun** [comment]
Hi,
   Sorry for late reply, This is not an error. Because the attribute `values` only not to represent. You can access it normally.
   
   I will update the docs quickly.

Thanks
