### ISSUE TITLE
Do you mind if I make some grammatical corections

### ISSUE THREAD

**Issue by mikeysan** [sns-sdks/python-facebook#67]
Hey, sorry I hit [enter] not knowing I would open the event before I finished typing. I have only just discovered your very awesome work in bringing us a Facebook API. I am currently reading through the readme file to learn how to use the API and have noticed a few typos that could use some correcting to help make reading easier.

Please let me know if this is okay, and I will proceed.

ps. I don't care about hacktoberfest, I just want to give back 😄

**Comment by MerleLiuKun** [comment]
hey, welcome for your pr. 😃
