### ISSUE TITLE
Migrate docs to mkdocs

### ISSUE THREAD

**Issue by MerleLiuKun** [sns-sdks/python-facebook#78]
Readme has too many words.

**Comment by triangle959** [comment]
could you leave chinese readme? i saw it yesterday

**Comment by MerleLiuKun** [comment]
hi, 

Now we are refactor the library, chinese readme is outdate, we will add when next docs updated.

If you are using version 0.9.x, You can go to branch `V0`. And see the readme.

**Comment by triangle959** [comment]
已收到
