### ISSUE TITLE
Inconsistent Fields being set for API requests

### ISSUE THREAD

**Issue by stevenviola** [sns-sdks/python-facebook#86]
I have noticed when using `IgProApi`, I am receiving different data on subsequent API requests. Usually this results in timestamps, media_urls, or media_types missing. In looking at the API calls being made, I can see that the fields being set are different every time I run the same script. Here's a minimal example: 

```
from pyfacebook import IgProApi
access_token = XXXXXXXX
account_id = 12345
api = IgProApi(
    long_term_token = access_token,
    debug_http=True,
    instagram_business_id=account_id
)
posts = api.discovery_user_medias(
    username='sandradewi88', 
    limit=1,
    count=1
)
```

This should be using the default fields but running the same script 3 times, the fields are completely different:

```
/v8.0/12345?fields=business_discovery.username(sandradewi88){media.limit(1){media_type,comments_count,username,media_url,children{media_type,timestamp,permalink,id},id,caption,like_count}}
```

```
/v8.0/12345?fields=business_discovery.username(sandradewi88){media.limit(1){like_count,timestamp,media_url,caption,permalink,children{timestamp,id,username,media_type,permalink},comments_count}}
```

```
/v8.0/12345?fields=business_discovery.username(sandradewi88){media.limit(1){caption,children{permalink,username,timestamp,media_type,media_url,id},comments_count,like_count,permalink,id}}
```

The default `INSTAGRAM_MEDIA_PUBLIC_FIELD` set looks correct and should contain the following fields:

```
{'media_url', 'media_type', 'username', 'children{media_type,username,permalink,media_url,timestamp,id}', 'comments_count', 'permalink', 'caption', 'like_count', 'timestamp', 'id'}
```

So I assume that in the `enf_comma_separated` function, the fields are being omitted, and that the `timestamp`, `media_type`,  or `media_url` in the "children" section is causing the function to deduplicate the fields for the parent post, or vice-versa.

`enf_comma_separated` should handle the case of the children fields being the same as the parent fields and not strip those from the field list.

**Comment by MerleLiuKun** [comment]
Hi, there are two problems.

First, Why fields complete different? because the default fields has been defined with the set type. and the set is unordered.

Secondly, if fields pointed with string, the `enf_comma_separated` function may have unexpected results. I will fix it quickly.

Thanks for you :),

**Comment by stevenviola** [comment]
@MerleLiuKun this is great, and I have confirmed this fixes the issue. I'm now able to see `media_type` and other fields being set for the media object, and the media children objects.

**Comment by stevenviola** [comment]
Are there any plan to update pypi with a new version that includes this fix?

**Comment by MerleLiuKun** [comment]
Sorry for late reply, I will publish a new version at this week. :)
