### ISSUE TITLE
Note: The order of the set is unreliable.

### ISSUE THREAD

**Issue by tomahocbc** [sns-sdks/python-facebook#89]
what that means i copy the code from the example

"""
    This show how to get facebook page public posts.
"""

import json

from pyfacebook import Api

# Use version 5+, Call API need app secret proof. So need provide your app secret.
# If not have, you can just use version 4.0.
APP_ID = "Your APP ID"
APP_SECRET = "Your APP SECRET"

ACCESS_TOKEN = "Your Access Token"

def get_posts(page_username):
    api = Api(
        app_id=APP_ID,
        app_secret=APP_SECRET,
        long_term_token=ACCESS_TOKEN,
    )
    data = api.get_page_posts(
        page_id=page_username,
        since_time="2020-05-01",
        count=None,
        limit=100,
        return_json=True,
    )
    return data

def processor():
    page_username = "WHO"
    data = get_posts(page_username)
    with open("wto_posts.json", 'w') as f:
        json.dump(data, f)

if __name__ == "__main__":
    processor()

**Comment by MerleLiuKun** [comment]
If you not provide the fields what you want to get data, The default fields provides by a set of fields. 

We know the order of a set is unreliable, 

You can ignore the note. Or you can provide fields param with list or tuple or string.
