### ISSUE TITLE
Future. Can you add the support of LeadGen object.

### ISSUE THREAD

**Issue by shizacat** [sns-sdks/python-facebook#9]
Hello.
Can you add the support of LeadGen object.

Yes, request is simple, but create model of object is not succeeded.
```
def get_leads(self, lead_id: str):
        target = lead_id
        resp = self._request(
            method='GET',
            path='{0}/{1}'.format(self.version, target)
        )
        data = self._parse_response(resp.content.decode('utf-8'))
        return data
```

**Comment by MerleLiuKun** [comment]
😊 Thanks for your issue. I will do it soon. :)

**Comment by MerleLiuKun** [comment]
@shizacat  Hi, I have read the docs. This belong marketing api. Becaese I have not many experience on this. So this will need some time. :)

If you need use now. You can use [Facebook Business SDK for Python](https://github.com/facebook/facebook-python-business-sdk). 

Thanks. And I will start work on it. :construction:
