### ISSUE TITLE
Question: is there a function to fetch a user's pages, from the User Accounts Endpoint.

### ISSUE THREAD

**Issue by JiGGie145** [sns-sdks/python-facebook#94]
Please correct me if I am just not seeing this in the code. But are there functions that call this functionality [User Accounts](https://developers.facebook.com/docs/graph-api/reference/user/accounts/) (`https://developers.facebook.com/docs/graph-api/reference/user/accounts/`) . 

**Context**: I have a user for whom I have the user-access-token and would like to only read data from pages that this user owns. I believe I would need to call this endpoint to retrieve those pages. So I would like to know if I have overlooked something and this functionality already exists in this library before going and implementing this myself.

**Comment by MerleLiuKun** [comment]
Yes, you can get a user all pages with the access token given by the user, use the endpoint `\me\accounts`.

But, this library not have this method now.:)
