### ISSUE TITLE
Question: Why aren't the 'from' and 'target' fields being returned to me?

### ISSUE THREAD

**Issue by nedsons** [sns-sdks/python-facebook#95]
I'm using the function "API.get_comments_by_object ()", but the fields "from" and "target" are not being returned. How do I get these fields returned? Is there any specific permission I need? I already have Facebook Publick Content Access permission.

**Comment by MerleLiuKun** [comment]
Hey，

     First, you need add `from` and `target` with the parameter `fields`.
     Second, you need set the parameter `return_json` to `True`, because the comment model now not format those field. So you need use the json data.:)

You can try this. :)

**Comment by nedsons** [comment]
Hi,

First of all, thanks for the help!
So, I put the `from` and `target` fields in the `fields` parameter, and I also set the `return_json` parameter to True. However, only "from" appears for some. Why don't you appear to others? Could it be that some permission is missing? Only shows only for some types of users? Here's a link to a Postman screenshoot to better understand what I'm talking about: [
![Screenshot of the Postman software when requesting comments on a post](https://user-images.githubusercontent.com/39832888/108100404-a445a400-7064-11eb-87cd-6b69452e9bff.png)

**Comment by MerleLiuKun** [comment]
Oh, that's facebook permissions. the fields `from` is private field now, You need more permissions to retrieve it.

Like this question: [Facebook Graph API is not returning (From) field for a comment](https://stackoverflow.com/questions/48732148/facebook-graph-api-is-not-returning-from-field-for-a-comment)

**Comment by nedsons** [comment]
I get it!
I entered the link you gave, but I couldn't understand. What exactly would be the permission I need? Because in the link you shared, the guy says that I need a page token, but with a page token I can't even get dat `GET `in the comments of a post. It just requires the `Page Public Content Access` permission (which I already have for the application token).

**Comment by MerleLiuKun** [comment]
As my known, If you get comments for a post use the post's page token, you can get `from` fields. 

If you use app token, if the target user have give an authorization for that app, you can get `from` field.

That's facebook limit. :smiley:

**Comment by nedsons** [comment]
Yes, this actualy is right. Thanks!
