### ISSUE TITLE
Error when using the function api.get_media_info: pyfacebook.error.PyFacebookException: FacebookException

### ISSUE THREAD

**Issue by nedsons** [sns-sdks/python-facebook#96]
Hi guys,

I'm having trouble collecting post information. According to [Instagram Reference Page of IG Media](https://developers.facebook.com/docs/instagram-api/reference/ig-media) I already meet all requirements (I think). However, I cannot collect the information using a valid post id, and also using a user token with the `instagram_basic`, `pages_read_engagement`, `pages_show_list `permissions and the `Instagram Puclic Content Access` feature. All have already gone through the app review. Even so, using the function `api.get_media_info` I get the following error message: `pyfacebook.error.PyFacebookException: FacebookException (code = 100, type = GraphMethodException, message = Unsupported get request. Object with ID '...' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api)`

Thanks!

Here is an image of the debugged access token:
![Sem título](https://user-images.githubusercontent.com/39832888/109817480-bd2b8900-7c10-11eb-8fb7-36210f3c99bc.png)

**Comment by MerleLiuKun** [comment]
Ok, 

For api `get_media_info`, You can only get media data for the media belong to the token user,

You can check this.

**Comment by nedsons** [comment]
This is not quite what the documentation says. In the documentation it says that the `owner` field will be returned only to the media owner, otherwise the` username` field will be returned. However, when I use the `api.get_hashtag_top_medias` function, the` username` field always comes `None`.

**Comment by MerleLiuKun** [comment]
If the `get_hashtag_top_medias` return your media, maybe have `username` field, I think. :smile:

**Comment by nedsons** [comment]
So, yes, the field comes, but there is always `None`. I looked better in the documents and found that this field will not be returned at all.
